controller/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler
from flask import Flask

from config import config_dict


# 设置日志(目的是将flask默认的日志和自定义的日志保存到文件中)
def setup_log(log_level):
    # 设置日志的记录等级
    logging.basicConfig(level=log_level)  # 根据配置类型设置日志等级

    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    if not os.path.exists('logs'):
        os.makedirs('logs')
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(pathname)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


# 工厂函数: 由外界提供物料, 在函数内部封装对象的创建过程
def create_app(config_type):  # 封装web应用的创建过程
    # 根据类型取出对应的配置子类
    config_class = config_dict[config_type]
    app = Flask(__name__)
    app.config.from_object(config_class)

    # 注册蓝图对象  如果内容只在文件中使用一次, 最好在使用前才导入, 可以有效避免导入错误
    from controller.modules.home import home_blu
    app.register_blueprint(home_blu)
    from controller.modules.user import user_blu
    app.register_blueprint(user_blu)

    # 设置日志
    setup_log(config_class.LOG_LEVEL)
    return app

controller/modules/home/__init__.py
from flask import Blueprint

# 创建蓝图对象
home_blu = Blueprint("home", __name__)

# 让视图函数和主程序建立关联
from controller.modules.home.views import *

controller/modules/home/views.py
from flask import session, render_template, redirect, url_for, Response
from controller.modules.home import home_blu
from controller.utils.camera import VideoCamera
import pygame.camera

video_camera = None
global_frame = None
global_id = 0

# 获取摄像头数量
pygame.camera.init()
camera_nums = len(pygame.camera.list_cameras())


# 主页
@home_blu.route('/')
def index():
    # 模板渲染
    username = session.get("username")
    ambient = round(28.88, 1)  # (sensor.get_ambient(),1) 室内温度
    temp = round(36.55, 1)  # (sensor.get_object_1(),1) 体温
    tempInfo = {
        'ambient': ambient,
        'temp': temp
    }
    # bus.close()

    if not username:
        return redirect(url_for("user.login"))
    return render_template("index.html", **tempInfo)


@home_blu.route('/change_camera')
def change_camera():
    global video_camera
    global global_id
    video_camera.__del__()
    global_id += 1

    video_camera = VideoCamera(global_id % camera_nums)
    return redirect(url_for("home.index"))


# 获取视频流
def video_stream():
    global video_camera
    global global_frame

    if video_camera is None:
        video_camera = VideoCamera()

    while True:
        if video_camera is not None:
            frame = video_camera.get_frame()
            if frame is not None:
                global_frame = frame
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
            else:
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + global_frame + b'\r\n\r\n')


# 视频流
@home_blu.route('/video_viewer')
def video_viewer():
    # 模板渲染
    username = session.get("username")
    # voice_alert()
    if not username:
        return redirect(url_for("user.login"))
    return Response(video_stream(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


def close_camera():
    global video_camera
    video_camera.__del__()
    video_camera = None

controller/modules/user/__init__.py
from flask import Blueprint

# 创建蓝图对象
user_blu = Blueprint("user", __name__)

# 让视图函数和主程序建立关联
from controller.modules.user.views import *

controller/modules/user/views.py
from flask import session, redirect, url_for, request, render_template

from controller.modules.user import user_blu
from controller.modules.home import close_camera


# 登录
@user_blu.route("/login", methods=["GET", "POST"])
def login():
    username = session.get("username")

    if username:
        return redirect(url_for("home.index"))

    if request.method == "GET":
        return render_template("login.html")
    # 获取参数
    username = request.form.get("username")
    password = request.form.get("password")
    # 校验参数
    if not all([username, password]):
        return render_template("login.html", errmsg="参数不足")

    # 校验对应的管理员用户数据
    if username == "admin" and password == "admin":
        # 验证通过
        session["username"] = username
        return redirect(url_for("home.index"))

    return render_template("login.html", errmsg="用户名或密码错误")


# 退出登录
@user_blu.route("/logout")
def logout():
    # 删除session数据
    session.pop("username", None)
    close_camera()
    # 返回登录页面
    return redirect(url_for("user.login"))

controller/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AI-MasKeeper</title>
    <link href="../static/css/style1.css" rel='stylesheet' type='text/css'/>
</head>
<body>
<div class="table_align">
    <table border="0">
        <tr>
            <td colspan="2" style="background-color:#27CCCC;">
                <h1>AI-MasKeeper——家用智能口罩佩戴检测提醒系统</h1>
            </td>
        </tr>
        <tr>
            <th rowspan="2" style="background-color:#5AE5E5	;height:500px;width:645px;">
                <!-- 显示视频流 -->
                <div>
                    <img id="video" src="{{ url_for('home.video_viewer') }}">
                </div>
            </th>
            <td style="height: 145px;background-color:#6fcaca;">
                <input type="button" class="btn" value="更改设备"
                       onclick="javascrtpt:window.location.href='{{ url_for('home.change_camera') }}'">
            </td>
            >
        </tr>

        <tr>
            <td>
                <!-- 天气 -->
                <div id="he-plugin-standard"></div>
                <script>
                    WIDGET = {
                        CONFIG: {
                            "layout": 2,
                            "width": "230",
                            "height": "345",
                            "background": 4,
                            "dataColor": "FFFFFF",
                            "backgroundColor": "35ABCF",
                            "language": "zh",
                            "key": "e5c250158b87402dbcc1015750c33b2e"
                        }
                    }
                </script>
                <script src="https://widget.heweather.net/standard/static/js/he-standard-common.js?v=1.1"></script>
            </td>
        </tr>

        <tr>
            <td colspan="2" style="background-color:#7ac3c9;">
                <input type="button" class="btn" value="退出系统"
                       onclick="javascrtpt:window.location.href='{{ url_for('user.logout') }}'">
            </td>
        </tr>
    </table>
</div>
 
<div class="div-parent">
    <style>
        .div-parent {
            width: 100%;
            background-color: rgba(170, 170, 170, 0);
        }

        .copy-rights {
            width: fit-content;
            height: 50px;
            background-color: rgba(0, 127, 255, 0);
            margin: 0 auto;
        }
    </style>
       
         
</div>
</body>
</html>

controller/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AI-MasKeeper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="../static/css/style.css" rel='stylesheet' type='text/css'/>
    <!--字体-->
    <link href='http://fonts.useso.com/css?family=PT+Sans:400,700,400italic,700italic|Oswald:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='http://fonts.useso.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
    <!--//js-->
    <script src="http://ajax.useso.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<script>$(document).ready(function (c) {
    $('.close').on('click', function (c) {
        $('.login-form').fadeOut('slow', function (c) {
            $('.login-form').remove();
        });
    });
});
</script>
<!--SIGN UP-->
<div style="width: 100%"><h1>AI-MasKeeper</h1></div>
<div class="login-form">
    <div class="close"></div>
    <div class="head-info">
        <label class="lbl-1"> </label>
        <label class="lbl-2"> </label>
        <label class="lbl-3"> </label>
    </div>
    <div class="clear"></div>
    <div class="avtar">
        <img src="../static/images/avtar.png"/>
    </div>
    <form method="post" action="{{ url_for("user.login") }}">
        <input type="text" class="text" name="username" value="Username" onfocus="this.value = '';"
               onblur="if (this.value == '') {this.value = 'Username';}">
        <div class="key">
            <input type="password" name="password" value="Passowrd" onfocus="this.value = '';"
                   onblur="if (this.value == '') {this.value = 'Password';}">
        </div>
        <div class="signin">
            <input type="submit" value="Login">
            {% if errmsg %} {# 判断是否有错误信息 #}

                <div class="error_tip" style="display: block;color: red">{{ errmsg }}</div>

            {% endif %}
        </div>
    </form>

</div>

</body>
</html>